# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-02 07:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import emailverification.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BouncedEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstbouncetime', models.DateTimeField(auto_now_add=True)),
                ('bounces', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, default=emailverification.models.make_key, max_length=12, unique=True)),
                ('pingtime', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('code', models.CharField(db_index=True, max_length=16)),
                ('searchkey', models.CharField(blank=True, db_index=True, max_length=127, null=True)),
                ('action', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_send', models.DateTimeField(auto_now_add=True)),
                ('hits', models.IntegerField(default=0)),
                ('retries', models.IntegerField(default=0)),
                ('killed', models.BooleanField(default=False)),
            ],
        ),
    ]
